dubbo:
  application:
    name: provide
  registry:
    address: zookeeper://127.0.0.1:2181

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

mybatis:
  type-aliases-package: com.mybatis.test.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true